name: 01-Terraform-Deployent

on: workflow_dispatch

jobs:
  terraform-deploy:
    runs-on: ubuntu-latest
    environment: aws

    steps: 
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup AWS credentials
        run: |
        


      - name: Terraform init 
        run: |
          echo "Terraform init phase"
          sh "terraform init"
      - name: Terraform plan
        run: |
          echo "Terraform plan phase"
          sh "terraform plan"


