name: 01-Terraform-Deployent

on: workflow_dispatch

jobs:
  terraform-deploy:
    runs-on: ubuntu-latest
    steps: 
      - name: Terraform init 
        run: |
          echo "Terraform init phase"
          sh "terraform init"
      - name: Terraform plan
        run: |
          echo "Terraform plan phase"
          sh "terraform plan"


