name: 01-Terraform-Deployent

on: 
  workflow_dispatch:
    inputs:
      deploy-choice:
        type: choice
        options:
          - apply
          - destroy
        description: To choose between apply and destroy

jobs:
  terraform-deploy:
    runs-on: ubuntu-latest
    environment: aws

    steps: 
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup AWS credentials
        run: |
          echo "AWS_ACCESS_KEY_ID=${{secrets.AWS_ACCESS_KEY_ID}}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{secrets.AWS_SECRET_ACCESS_KEY}}" >> $GITHUB_ENV
          echo "AWS_DEFAULT_REGION=${{secrets.AWS_REGION}}" >> $GITHUB_ENV
          export AWS_ACCESS_KEY_ID=${{secrets.AWS_ACCESS_KEY_ID}}
          export AWS_SECRET_ACCESS_KEY=${{secrets.AWS_SECRET_ACCESS_KEY}}
          export AWS_DEFAULT_REGION=${{secrets.AWS_REGION}}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform
        with: 
          terraform_version: 1.0.0
     
      - name: Terraform init 
        run: |
          echo "Terraform init phase"
          terraform init
     
      - name: Terraform plan
        run: |
          echo "Terraform plan phase"
          terraform plan

      - name: Terraform apply or destroy
        run: |
          echo "Terraform apply or destroy phase"
          terraform ${{inputs.deploy-choice}} --auto-approve


